[package]
name = "test-harness"
version = "0.1.0"
edition = "2018"

[features]
default = []

vendored = ["ms-tpm-20-ref/vendored"]

[dependencies]
ms-tpm-20-ref = { path = "../" }

pretty_env_logger = "0.4.0"
log = "0.4"
